FROM php:7.2-fpm
RUN apt-get update
RUN apt-get install -y vim zip unzip iputils-ping \
  git curl gnupg nodejs npm
RUN npm install n -g && n stable
RUN docker-php-ext-install pdo_mysql mysqli mbstring && \
RUN  pecl install xdebug
RUN  docker-php-ext-enable xdebug