FROM php:7.2-fpm
RUN apt-get update
RUN apt-get install -y vim zip unzip iputils-ping \
  git curl gnupg nodejs npm
RUN npm install n -g && n stable
RUN docker-php-ext-install pdo_mysql mysqli
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer